### ISSUE TITLE
[needs to be vetted] [home page improvements] Gradual new templating and bootstrap 5 plan of action

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1206]
# Rewrite

Gradual new templating and bootstrap 5 plan of action

- [x] Split up blocks that can be loaded separately
- [x] Port prototype to bootstrap 5 and update issues [in progress]
- [x] Rewrite each block in new template
- [x] Write css in bootstrap 5
- [x] Add bootstrap 5 css pipeline (still needed?)
- [ ] Lazy load each block

**Comment by mietcls** [comment]
@nics can this one be closed or do we still need to add anything?

**Comment by nics** [comment]
@mietcls can be closed, the dashboard components are lazy loaded
