### ISSUE TITLE
[Epic] As a researcher or supervisor, I can complete and publish records with a quick-view (use case: Plato)

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1280]
# Epic
As a researcher or supervisor, I can complete and publish records with a quick-view (use case: Plato)

# Claiming and importing

- [ ] When I decide to import a (Plato) record and click "claim",
  - [ ] it automatically is added as a draft
  - [ ] it is removed from the import suggestions
  - [ ] it is shown in the activity list

## Filling out the basics
- [ ] When I decide to import a (Plato) record and click "claim", I as a researcher/administrative support only need to fill out the fields that are needed an I have control over (AKA Quick view) [Plato imports]
- [ ] Scrollspy
- [ ] Full view
- [ ] When I decide to import a (Plato) record and click "complete", I can decide to publish it or save it as a draft

Notes
- smart access levels
- sidebar
  - message
  - history
  - info
- thumbnail
- topbar in citation style

**Comment by mietcls** [comment]
Outdated
