### ISSUE TITLE
Epic: Plato imports phase 2: researchers

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1348]
# Epic: Plato imports phase 2: researchers
[Plato integration milestone](https://github.com/ugent-library/biblio-backoffice/milestone/11): automatically ingest dissertations in Plato, help researchers to complete.
![Screenshot 2024-07-29 at 12 22 42](https://github.com/user-attachments/assets/2d228571-82cb-4f29-841f-b2c74eaa58e0)

Prototype:
https://booktower-ugent-ui.vercel.app/biblio/researcher/dashboard/dashboard.html

## Scope: feature flag for a predefined group of people and for a certain amount of time.

- **Phase 1: Q3** We will roll out this suggestions for a defined group of people via feature flags so we can keep track of expectations and issues: TW
  - [x] `13 September` Test release suggestions, internally
  - [x] `23 September` Production release, faculty TW only
  - [x] `8 October` Production release proxies
- **Phase 2: Q4** After a predefined amount of time, we roll it out for all researchers.
  - [x] `19 November` Production release, all faculties + proxies

## Seeing research you contributed to and your role

- [x] https://github.com/ugent-library/biblio-backoffice/issues/1278
- [x] #408

_In order to make sure people add the requested missing information and claim outstanding research, involved parties (author, supervisors) should be able to see the suggested Plato imports. This is needed, because promotors assist often in filling out the information in Biblio._

## Suggesting and claiming dissertations

**Priority 1**

- [x] #1672
- [x] #1279
- [x] #1669

**Priority 2**

- [x] #1676
- [x] #1703 

**Priority 3**

- [x] #1704

## Experiment: rights management – Simple proxies
- [x] #1675
- [Simple Proxies] Add suggestions to proxies
_see https://github.com/ugent-library/biblio-backoffice/issues/1689_
  - [x] Add suggestions to sidebar https://booktower-ugent-ui.vercel.app/biblio/researcher/publications/overview--proxy.html
  - [x] #1712

https://booktower-ugent-ui.vercel.app/biblio/researcher/researcher-suggestions/researcher-suggestions--proxy.html
<img width="1512" alt="Screenshot 2024-08-23 at 12 09 27" src="https://github.com/user-attachments/assets/e9ae9c39-0615-49d5-abd3-13af4fef499a">

https://booktower-ugent-ui.vercel.app/biblio/researcher/proxies/proxies.html
<img width="1512" alt="Screenshot 2024-08-23 at 11 57 54" src="https://github.com/user-attachments/assets/74c71949-9bdf-4d2e-85a9-f5a6f5f05920">

# Out of scope
- Quick view on regular search and detail pages
- Search and filter on import page (will probably not be needed after initial batch)
- Advanced delegations for broader research community (administrative support etc)
- Suggested departments
