### ISSUE TITLE
[epic][templ] Templ Refactor overview

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1487]
# Epic

Templ Refactor overview. 
Board: https://github.com/orgs/ugent-library/projects/9

# Easiest order

1. search and show pages
2. import pages (these use templates from search and show)
3. after this the display package is no longer needed
4. delete templates (these generally use the view templates that are already refactored)
5. edit templates and update routes (on success these generally use the view templates that are already refactored)
6. after that the forms package is no longer needed

So forms last.

Look at how the display package is replaced by components to get inspiration for the forms package refactor.

When are we done? If there are no more imports of the `render` package.

# Areas

[✔️ = covered by Cypress tests] 

## Smaller and isolated refactors

- [x] https://github.com/ugent-library/biblio-backoffice/issues/1452
- [x] User dashboard
- [x] https://github.com/ugent-library/biblio-backoffice/issues/1438
- [x] https://github.com/ugent-library/biblio-backoffice/issues/1452

---

Smaller issues (covered in https://github.com/ugent-library/biblio-backoffice/issues/1402)

- [x] views/error_dialog.gohtml ✔️
  #1481 
- [x] views/form_errors_dialog.gohtml
#1554
- [x] #1498
- [x] views/dataset/add_department.gohtml ✔️
  #1454
  - [x] views/dataset/_suggest_departments.gohtml ✔️
- [x] views/dataset/add_project.gohtml
  #1472 
  - [x] views/dataset/_suggest_projects.gohtml
- [x] views/dataset/add_publication.gohtml ✔️
  - [x] #1486
- [x] views/dataset/confirm_delete_abstract.gohtml ✔️
  #1444
- [x] views/dataset/confirm_delete_contributor.gohtml ✔️
  #1426 
_(other contributor related views have far more dependencies so are probably out of scope of this ticket)_
- [x] views/dataset/confirm_delete_department.gohtml ✔️
  #1461
- [x] views/dataset/confirm_delete_link.gohtml ✔️
  #1460 
- [x] views/dataset/confirm_delete_project.gohtml ✔️
  #1466 
- [x] views/dataset/confirm_delete_publication.gohtml ✔️
  #1465 
- [x] views/dataset/confirm_delete.gohtml ✔️
#1422 
- [x] views/dataset/confirm_publish.gohtml ✔️
  #1413 
- [x] views/dataset/confirm_republish.gohtml ✔️
  #1413 
- [x] views/dataset/confirm_withdraw.gohtml ✔️
  #1410 
- [x] views/media_types/suggest.gohtml ✔️
  #1424 
- [x] views/modals/error.gohtml
- [x] views/publication/add_datasets.gohtml ✔️
#1504
  - [x] views/publication/_suggest_datasets.gohtml ✔️
- [x] views/publication/add_department.gohtml ✔️
  #1456 
  - [x] views/publication/_suggest_departments.gohtml ✔️
- [x] views/publication/add_project.gohtml
  #1473 
  - [x] views/publication/_suggest_projects.gohtml
- [x] views/publication/confirm_delete_abstract.gohtml ✔️
  #1437 
- [x] views/publication/confirm_delete_contributor.gohtml ✔️
  #1425 
_(other contributor related views have far more dependencies so are probably out of scope of this ticket)_
- [x] views/publication/confirm_delete_dataset.gohtml ✔️
  #1464 
- [x] views/publication/confirm_delete_department.gohtml ✔️
  #1462 
- [x] views/publication/confirm_delete_file.gohtml
  #1469
- [x] views/publication/confirm_delete_lay_summary.gohtml ✔️
  #1443 
- [x] views/publication/confirm_delete_link.gohtml ✔️
  #1441
- [x] views/publication/confirm_delete_project.gohtml ✔️
  #1467 
- [x] views/publication/confirm_delete.gohtml ✔️
  #1421 
- [x] views/publication/confirm_publish.gohtml ✔️
  #1415 
- [x] views/publication/confirm_republish.gohtml ✔️
  #1417 
- [x] views/publication/confirm_update_type.gohtml ✔️
  #1419 
- [x] views/publication/confirm_withdraw.gohtml ✔️
  #1410
- [x] views/publication/pages/add.gohtml
  #1485 
  - [x] views/publication/add_multiple_sidebar.gohtml (TODO: remove .gohtml file)
  - [x] views/publication/add_single_sidebar.gohtml (TODO: remove .gohtml file)
  - [x] views/publication/pages/add_wos.gohtml
  - [x] views/publication/pages/add_identifier.gohtml
  - [x] views/publication/pages/add_manual.gohtml
  - [x] views/publication/pages/add_bibtex.gohtml
- [x] `views/dashboard/*/*.gohtml`
  #1438
- [x] #1442
- [x] #1452
- [x] #1457

## Larger refactors

- [x] https://github.com/ugent-library/biblio-backoffice/pull/1475
- [x] publication search result pages
- [x] dataset show pages (can be done tab by tab)
  - [x] #1508
  - [x] #1511
  - [x] #1503
  - [x] #1502
  - [x] https://github.com/ugent-library/biblio-backoffice/issues/1498 (Biblio messages/activity)
- [x] #1488 
- [x] #1516
- [x] #1492
- [x] #1523
- [x] #1500
- [x] #1543
- [x] #1545
- [x] #1550
- [x] #1556
- [x] #1533
- [x] #1536
- [x] #1496
- [x] #1497
- [x] #1524
- [x] #1526
- [x] #1532
- [x] #1541
- [x] #1530
- [x] #1520
- [x] #1559
- [x] #1553
- [x] #1504
- [x] #1501
- [x] #1563

## Cleanup after refactor

- [x] remove display package
- [x] remove render package
- [x] remove forms package
- [x] remove funcmaps
- [x] remove gohtml files
- [x] remove old Contexts, Base, Handlers, Yield structs

# Comms flow

Suggestion?

- Pick area, check overview issue
- Start -> checkbox to issue, assign yourself, add to project, warn if needed
- Finish -> review PR (TBD wie reviewed wat)
- If ok -> Integrated testing (batch some PRs)
- Deploy once a week -> manual testing

Timing

- Dedicated templ time per week?
- Internal deadline?

**Comment by nics** [comment]
@mietcls the main layout already has a templ version
