### ISSUE TITLE
As a reviewer, I can motivate researchers to complete missing or faulty data in their publications

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#347]
# Story [In progress]

## Main story
As a reviewer, I can motivate researchers to complete their publications with the correct metadata, so the research, researcher, department and the university get the bibliographic, academic, financial and social recognition it deserves.

- Bibliographic: correct metadata, optimised for libraries and search engines – so interested parties can find it.
- Academic: recognition of research, university 
- Financial: grants and support
- Social: attribution for the stakeholders (resumés etc) 

## Sub stories

- As a reviewer, I can request the involved researchers to make changes in their record, so the record is complete to submit for resumés, search engines and grants.
- As a reviewer, I can hide publications from public resumés, search engines and grant summaries without having to break our persistent handle links, so faulty or incomplete records do not pollute search engines, the UGent Biblio site, resumés or get picked up in the grant workflows.
- As a reviewer, I can withdraw a record if it contains damaging information (eg. copyright issues), so we avoid lawsuits and contain the spread of wrongful information.

# Success criteria

## A reviewer can...
- [ ] **see which fields are missing information**, relevant to the specific record.
- [ ] **communicate with the authors and editors** responsible for this record.
- [ ] **adapt statuses to influence the visibility of a record**, as strict as needed for the specific case.
- [ ] **adapt statuses of a record** for their own workflow.
- [ ] **use statuses and messages** to motivate researchers to adapt records.

## A researcher...
- [ ] gets informed by the status of their record, and receives a message that motivates that message.
- [ ] can see which fields are missing information, relevant to their record.
- [ ] can reply to messages from a reviewer (and ask questions up front?).

### Adapting by researcher
- [ ] MVP: A researcher can deliver the requested information for their record to the reviewer.
- [ ] Future: A researcher can adapt the requested information in their record.

# Cases

- Case 0:  Private & Draft – researcher can view new private record
#348
- Case 1: Published & In Review – reviewers sees new record arrive workflow
#351 
- Case 2: Published & Validated – reviewer (adapts and) approves completed record
#353 
- Case 3: Published & Pending request – reviewer requests researcher to complete record
#354 
- Case 4: Unlisted & Pending request - reviewer requests researcher to add "breaking" information record
#355 
- Case 5: Private & Withdrawn - damaging record
#356
