### ISSUE TITLE
I can add authors and editors to a record.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#397]
# Design epic

I can add authors, editors and entities to a record, so the SEO can be optimised and the involved researchers from UGent see the record appear in their resume.

## Detail story 
When I add authors, editors or entities to my record, it automatically suggests UGent profiles whenever their names can be found in our UGent database.

# Implementation

## Overview

![Image](https://user-images.githubusercontent.com/1572885/185435278-c06631b7-6479-4d0c-a334-dc36bf0a4178.png)

[View code](https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publication-detail/description.html#authors-editors) and implement with remarks:
- Do not add sequence options (feature parity first)
- Add affiliation in overview (see #465 )

## Add authors

![Image](https://user-images.githubusercontent.com/1572885/185439991-e97726eb-76f3-4498-b7ad-88103e036072.png)

![Image](https://user-images.githubusercontent.com/1572885/185437256-62e754de-84ba-4c9a-b570-b07178f61eb9.png)

![Image](https://user-images.githubusercontent.com/1572885/185437542-e0d76c14-71b0-45cf-8756-190e6403c03d.png)

[View code](https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publication-detail/description.html?#authors-editors) and implement with remarks:
- Change title to "Add authors" (plural)
- Always scroll to last added author or form field of author outside of UGent upon add
- Add button "Add external author" below search field
- If we cannot find the right author, give the immediate option to add an external author in the list (as depicted in the prototype).

### To figure out: z-index dropdown does not work properly

![Image](https://user-images.githubusercontent.com/1572885/185436979-6043f404-7820-4149-a848-a69f845c664b.png)

## Add author from outside UGent

![Image](https://user-images.githubusercontent.com/1572885/185439776-8dc3a4c7-76ab-46a9-aa5d-ec6778abd634.png)

[View code](https://biblio-ugent-prototype-emily-v2.vercel.app/biblio/reviewer/publication-detail/description.html?#authors-editors) and implement with remarks:
- Always scroll to last added author or form field of author outside of UGent upon add

# Success Criteria

- [ ] I can easily add multiple people, it does not require a lot of clicking around (sometimes we have over a 100 authors for one publication)

## Part of UGent
- [ ] I can look for authors, editors and entities by searching on full name (in the back, is this a combination of for example first name and optionally last name) or ID.
- [ ] Names of authors, editors and entities that are part of the UGent are automatically suggested.
- [ ] I get helpful information about the researcher and entity, so in case there are multiple people with the same name, I can select the right person:
  - [ ] UGent ID (can be multiple IDs)
  - [ ] Department
  - [ ] Personal Details [Biblio authors](https://biblio.ugent.be/person/976604880752)
- [ ] Whenever this name is found multiple times in the database, I can get more information by clicking on their [Biblio profile](https://biblio.ugent.be/person/976604880752) and make an informed decision.
- [ ] [for reviewers and curators only] Whenever I still do not have enough information, I can add a name without an affiliation (reviewer perspective)
- [ ] I do not need to explicitly confirm someone is part of UGent, if this name is already in the UGent database.
- [ ] When I know someone is part of the UGent, but their name can not be found in the UGent database, I can add their name regardless and select them as an UGent researcher (for example someone from 30 years ago).
- [ ] There is an explanation available that explains to me how the UGent affiliation rules work.

## Not part of UGent
- [ ] When I want to add a name of a person or entity that is not part of the UGent, I can add them as an external researcher or entity. We fill out the first name or entity name, and give last name as optional.
- [ ] When I want to add a name of a person or entity that can be found in the UGent database, but was not part of the research as an UGent researcher, I can select them as an external researcher or entity. We fill out the first name or entity name, and give last name as optional.

## Editing
- [ ] I can remove an author, editor or entity that I accidentally added.
- [ ] I can switch the credit role of an author, editor or entity.
- [ ] I can switch the affiliation status (author, editor, entity) from UGent to external and back.

## Credit roles
- [ ] I can easily add the role of the author
  - First author
  - Last author
  - Conceptualization
  - Datacuration
  - Formal analysis
  - Funding acquisition
  - Investigation
  - Methodology
  - Project administration
  - Resources
  - Software
  - Supervision
  - Validation
  - Visualization
  - Writing - original draft
  - Writing - review and editing

# Out of scope
- Make sure we can add authors and editors by full name; and catch cases where people fill out last name before first name
- Editing the department in the overview
- TO BE DISCUSSED: Adding the department of an author that is not found in the UGent database if they are part of UGent (Does this happen often?) -> can be solved now by adding it to the departments overview.

# Context

## Accessibility
- Make sure there is an explicit "button" when needed. The action should be clear for screen readers, and in correct HTML (no divs etc in a button).

## Context stories
- I am invited to add records to Biblio, so it can easily be found in search engines.
- I am invited to add records to Biblio, so my resumé is complete.
- When I add records to Biblio, I am invited to add all authors, editors and entities to the record, so it appears in their resumé and they don't need to add it themselves again.

## Current new implementation

Adding one person, no doubles
- Click on "add", fill out first- and last name, add role, select if UGent or not ![Image](https://user-images.githubusercontent.com/1572885/169266487-fc50973f-9459-4ccb-9cac-e37522702b21.png)
- Confirm author, view details (missing: personal details link) ![Image](https://user-images.githubusercontent.com/1572885/169266566-9c44fb93-61ff-4007-b4f8-f93f2ad95dd2.png)
- If confirmed as UGent researcher, the fields lock (missing: department number confirmation)

Doubles
-  Confirm author, view details (missing: personal details link) ![Image](https://user-images.githubusercontent.com/1572885/169266918-bd0e55b7-5414-46d2-ac8d-609a700296cf.png)

Editing
- Same way as adding a new author, editor or entity. However I cannot change the person I selected or added  – only the role or affiliation.

![Image](https://user-images.githubusercontent.com/1572885/169267221-4eba1203-9965-4542-a43b-9462de7a2c33.png)
![Image](https://user-images.githubusercontent.com/1572885/169267241-a2095760-0901-4d21-8584-ca9fc8556948.png)

Delete
- Confirmation ![Image](https://user-images.githubusercontent.com/1572885/169267004-b5329f1b-e514-4aea-a3c5-27b4d202cdf6.png)

## Current implementation in old back-end

Adding one person, no doubles
- Click on "plus" on any record ![Image](https://user-images.githubusercontent.com/1572885/169259727-6092c6b7-4376-43b0-8a97-f07dab4dc833.png)

- Fill out first- and last name ![Image](https://user-images.githubusercontent.com/1572885/169259859-a40d80bb-ec57-4817-b05d-2c05c80def61.png)
- Indicate UGent if applicable, automatically retrieve department number if there is only one person with that name ![Image](https://user-images.githubusercontent.com/1572885/169259988-7c8381be-e3cf-4e17-a2b9-2f48c0559739.png)

Doubles
- Pick the right author, get more info if needed ![Image](https://user-images.githubusercontent.com/1572885/169259044-23653319-2b0f-4f11-b9c5-2b82be14d9ed.png)

Cannot find author
- Held back ![Image](https://user-images.githubusercontent.com/1572885/169260421-a83ed571-51a8-425a-95d3-8963dc333f8b.png)

Delete
- Click "minus" icon, no warning.

## Outstanding questions

**Would more links come in handy, linking to other portals such as phone book, ORCID iD, research portal?** Such as  (or UGent [telephone book](https://telefoonboek.prd.rad.ugent.be/nl/simple) or [research portal](https://research.ugent.be/web/search-person))
Not needed

**Do we also need to allow searching for middle names and initials?**
We should give as much freedom as possible, and even leave last names open

**Do we also need to allow searching for IDs?**
Can be shown in the design

**Should we allow people to be added as an author or editor whenever they are not found in the UGent database?**
Yes

**Comment by emilyvandewalle** [comment]
## Design proposal

The designs for this issue can be found [here](https://www.figma.com/file/YKfocx0xpkuuyQUa3qt70P/Biblio---Final-issues?node-id=3%3A1212)


**1. Offer choice between selecting from UGent database or adding "Other" author**

Since you both need to be able to select from the database and add an author that is external/not in the UGent database I propose a button toggle at the top which changes the controls underneath

![image](https://user-images.githubusercontent.com/36261498/176456179-5e6a3919-a046-49da-82d1-bf490c4ccd4b.png)

**2. Selecting an author from the UGent database**

The idea for selecting an author from the UGent database is that a search field shows an autocomplete list of authors once you start typing:

![image](https://user-images.githubusercontent.com/36261498/176456203-4ee148f5-f8db-4a35-9e65-1c4fe4b251a6.png)

You can select the author or visit an external link to view the profile for more information if needed:

![image](https://user-images.githubusercontent.com/36261498/176465604-8ea7a700-e9af-467f-b4c9-8fa327cbe47f.png)

You can add multiple authors at once. Each selected author shows up in the list underneath where you can choose the role and mark whether the author was an external researcher during the time of the publication:

![image](https://user-images.githubusercontent.com/36261498/176465976-3703a092-8554-4373-9d9c-97aec20f6a55.png)

**3. Adding other author**

When "Other author" is selected, the modal shows open input fields for the first name/entity name (mandatory) and last name (optional). You can also mark whether the author was part of UGent during the time of the publication:

![image](https://user-images.githubusercontent.com/36261498/176459023-e4944a10-789f-4742-8ed5-c353491eac0e.png)

We could also enable adding multiple authors at once here by showing a button to add another author which could add a new form underneath:

![image](https://user-images.githubusercontent.com/36261498/176466014-3beaaa57-b165-4a76-942f-7e038c516797.png)

![image](https://user-images.githubusercontent.com/36261498/176466094-d5c1cfc3-c76e-4fdf-87b7-a25e790b90bc.png)


## More details 

For the autocomplete list there currently is an explicit button to select the author, alternatively I was thinking if we could make the button to select the author only visible on hover:

![image](https://user-images.githubusercontent.com/36261498/176458837-eb2bb576-2730-42b6-a3e0-22d6b521150d.png)

Or (although not sure if this would be correct in terms of accessibility) absolute position a button inside of an author list item so there's semantically a button and the selection of an item is keyboard accessible, but it's not visible, something like this:

```
<ul>
   <li>
        <button class=”u-sr-button”></button>
        <h4>Jane Doe</h4>
        <p>Department...</p>
         ...
   </li>
   ....
</ul>
```

```
li {
   position: relative;
}
li .u-sr-button {
   position: absolute;
   top: 0;
   right: 0;
   bottom: 0;
   left: 0;
   width: 100%;
   height: 100%;
}
```

## Questions
- What is your overall feedback on the proposed flow?
- What are your thoughts on the toggle to either select from the database or to add another author?
- Can an author/person have multiple departments?
- Should I look further into the alternatives for the explicit button to select an author?

**Comment by mietcls** [comment]
**The overall design**
The overall design seems good to me. We might try to shuffle the elements around a bit during implementation. Unless I missed something @nics & @netsensei?

**The toggle on top**
I’m afraid this one might accidentally get skipped when adding a lot of people (e.g. an administrative profile adding 30 publications with all authors). What I’d propose here is
- The researcher starts typing in the search box
- The researcher can’t find the author (because it is not in our database)
- The interface shows the option “add author from outside UGent”
- The researcher sees the form “adding other author”

I think you had something similar before; we might have given conflicting input here.

**Adding multiple researchers**
This seems quick! With the feedback above it would be the same behaviour for each type of author (as you suggested with select or add UGent author).

**Removing the button until hover**
For simplicity I would keep the button there for now. But this is a good path to explore.

**Implementation**
We might need some help here to be able to create those flexible cards (see #400 ).

**Comment by nics** [comment]
@mietcls @emilyvandewalle huge improvement over the current dialog

**Comment by nics** [comment]
this proposal addresses the corporate name issue and is much more elegant, but maybe doesn't handle the 'i know only the full name' case?

**Comment by mietcls** [comment]
Aha, right. We also don't have a field for middle names which some people expect to input as well. But we have the elements, we can shuffle them around.

**Comment by mietcls** [comment]
Thank you for iterating on this solution, we can go full steam ahead with this!

For your information:

- Information sequence: if we're worried about the sequence of information, we can just put them vertically with some spacing. It seems to work for existing UGent authors as well, and to me it feels like one would forget about filling the inputs out less easily.

![Image](https://user-images.githubusercontent.com/1572885/185430965-f47ca66a-2a3d-4f03-b124-401efa464328.png)

- "UGent author outside of UGent"
I've experimented a bit myself to see what the solution would be.

1. Adding the "Add author from outside UGent" allows people to add someone if they can't find it in the list immediately.
2. However, if it's known beforehand that this person is from outside of UGent it's annoying to type it twice and not being able to reuse the information (we do not have that infrastructure yet). So we should probably keep both patterns – the button and the dropdown option to add someone outside of the organisation.

No need to adapt anything in the prototype, we'll figure it out and save your time for when we are really in the trenches 😉 

One remark: the dropdown's z-index does not seem to work. I'll try to figure out what the issue is!

**Comment by mietcls** [comment]
@nics & @netsensei is the story on top clear, and is the size okay, so we can move it to "ready for launch"? Or should I adapt something?

No need to read the entire conversation, I just kept it for reference. I can also split this up in the future and refer to this story instead of reusing it.

**Comment by mietcls** [comment]
Split up
- cosmetic
- new functionality

**Comment by nics** [comment]
@mietcls is this still relevant or can it be closed?

**Comment by mietcls** [comment]
@nics I'll make new issues for the out-of-scope remarks that are in here (full name vs first- last name, orcid, "participated as external author")
