### ISSUE TITLE
Blank states

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#545]
# Epic

To inform users about what is wrong or what they need to do, we need a couple of blank states:

- [x] https://github.com/ugent-library/biblio-backend/issues/544
No results or data (nothing to show) 
- [ ] https://github.com/ugent-library/biblio-backend/issues/549
Error (something went wrong) – to refine
- [ ] https://github.com/ugent-library/biblio-backend/issues/551
First use (this is what you need to do) – nice to have
- [ ] https://github.com/ugent-library/biblio-backend/issues/610
Loading states – nice to have
- [ ] https://github.com/ugent-library/biblio-backend/issues/662
Mixed message to give the possibility to simplify code
- [x] #664 
Page does not exist
- [ ] #665 
Downtime page

Question: which ones are "feature parity"?

## Component
Pick according to the required blank states:
https://biblio-ugent-prototype-emily-v2.vercel.app/styleguide/c-blank-slate.html

## Example code
Layout should be adapted by the type of blank state, see component.

Inside the card body:

```
<div class="card-body p-0">
  <div class="c-blank-slate c-blank-slate-large c-blank-slate-muted">
    <div class="bc-avatar bc-avatar--medium">
      <i class="if if-info-circle"></I>
    </div>
    <h1>No records found.</h1>
    <p>Adjust your search or filter to find what you are looking for.</p>
  </div>
</div>
```

**Comment by mietcls** [comment]
No answers, making this a stale issue.
