### ISSUE TITLE
Document details for full text flow + new publication policy

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#559]
# Story

When I enter document details for the files I upload, I am guided through the different blocks of information I have to provide:
- Document type
- Publication version
- Access level (with or without embargo)
- License (cc or not)

_Note: this is an elaborate design iteration, that can still simplify. We iterate in design before we decide on iteration to not have to pivot after implementation, but can do so before if needed._

## Success criteria
- [ ] Researchers and administrative support can make an informed decision based on the type of document they upload and, if applicable, the limitations installed by their publisher.
- [ ] The information is grouped in a logical way to make sure:
  - [ ] Researchers and administrative support do not see any superfluous information that does not apply to their specific case
  - [ ] So development-wise we can easily hide and show information in a conditional way

## To do
- Discuss possibilities conditional fields
- Confirm legal possibilities for opt-out behaviour (≠ regulation opt-in)
- Confirm cognitive load reduction
- Explore possibilities of reducing cognitive load even more
- Required fields
- Error states

# Decision tree

- Simple flow: https://www.figma.com/file/T2gsB1KY7d7V2beB2wavzk/Full-text-%26-attachments?node-id=1%3A25
- Conditional values: https://www.figma.com/file/T2gsB1KY7d7V2beB2wavzk/Full-text-%26-attachments?node-id=30%3A1982
- Textual: https://www.figma.com/file/T2gsB1KY7d7V2beB2wavzk/Full-text-%26-attachments?node-id=31%3A4977

Static simple flow (see above links for live documents):
<img width="1945" alt="02 Flowchart · flowchart simple v2" src="https://user-images.githubusercontent.com/1572885/189654493-d8bb4b25-b9fa-4aec-8fab-289e269e433a.png">

# Sketches
- Mapping: https://www.figma.com/file/T2gsB1KY7d7V2beB2wavzk/Full-text-%26-attachments?node-id=4%3A1382
- Upload: https://www.figma.com/file/T2gsB1KY7d7V2beB2wavzk/Full-text-%26-attachments?node-id=4%3A1659
- Document type & publication version: https://www.figma.com/file/T2gsB1KY7d7V2beB2wavzk/Full-text-%26-attachments?node-id=4%3A1672
- Access level: https://www.figma.com/file/T2gsB1KY7d7V2beB2wavzk/Full-text-%26-attachments?node-id=13%3A965
- License for open access files: https://www.figma.com/file/T2gsB1KY7d7V2beB2wavzk/Full-text-%26-attachments?node-id=16%3A572
- License for closed or local files: https://www.figma.com/file/T2gsB1KY7d7V2beB2wavzk/Full-text-%26-attachments?node-id=16%3A596

Static designs (see above links for live documents):
<img width="1404" alt="Sketch 1 - upload" src="https://user-images.githubusercontent.com/1572885/189654763-e7d4e454-e49a-4ecc-bfcb-efc93e246c7e.png">
<img width="1404" alt="Sketch 2 - doc type + version" src="https://user-images.githubusercontent.com/1572885/189654767-cdf998bf-f832-471f-abf0-dbd0c483bf0f.png">
<img width="1404" alt="Sketch 3 - access level" src="https://user-images.githubusercontent.com/1572885/189654769-c06bae23-b55b-410d-b94d-4190e2a194f0.png">
<img width="1404" alt="Sketch 4 - license for open access" src="https://user-images.githubusercontent.com/1572885/189654784-f826aace-bdbd-426f-a2f8-1a7429eb2d9b.png">
<img width="1404" alt="Sketch 5 - license for closed or local" src="https://user-images.githubusercontent.com/1572885/189654787-a0d11e66-a1a5-4512-9720-2299cd745ae8.png">

# Context

- https://github.com/ugent-library/biblio-backend/issues/481 (larger discussion + SPDX)
- https://github.com/ugent-library/biblio-backend/issues/440 (opt-out)
- https://github.com/ugent-library/biblio-backend/issues/240 (SPDX)
- https://github.com/ugent-library/biblio-backend/issues/139 (licenses)
- https://github.com/ugent-library/biblio-backend/issues/248 (cc licenses)
- https://github.com/ugent-library/biblio-backend/issues/249 (in copyright licenses)

**Comment by mietcls** [comment]
Embargoed access would be handy to search, we also need to know what the access level is before that

**Comment by mietcls** [comment]
Ask about deposit mandate; if it is still needed

# Old Biblio
![Schermafbeelding 2022-09-08 om 15 14 11](https://user-images.githubusercontent.com/1572885/189131441-3ca91c35-2dbe-4fde-93d9-256bf2127d50.png)

Problem: a lot of info, again a form question.

# New Biblio suggestion
<img width="1295" alt="Schermafbeelding 2022-09-08 om 15 12 36" src="https://user-images.githubusercontent.com/1572885/189131129-e9d87352-8557-462c-b359-b265df8e486f.png">

## Code

To be placed above the card.
```
<div class="alert alert-info">
  <i class="if if-info-circle-filled"></I>
  <p>By uploading files here, you give UGent permission to store this file and make it available to the public according to the <a href="https://www.ugent.be/intranet/nl/op-het-werk/bibliotheek/biblio/id-oa-mandaat.htm#" target="_blank">UGent Deposit Mandate</a>.
  </p>
</div>

```

**Comment by mietcls** [comment]
Should we add a "I don't know" option to the license?

**Comment by mietcls** [comment]
# Old sketches as base of this rework

## 1. Upload full text or document
Drag & drop or select from file browser

![Image](https://user-images.githubusercontent.com/1572885/188590330-02420bf6-c8f2-4156-b107-3d3b057f66bd.png)

## 2. Select document type (AKA relation) and version

![Image](https://user-images.githubusercontent.com/1572885/188590392-2be90bce-9b7c-4952-806a-a044430a6ed9.png)

- [ ] Select document type
- [ ] Select publication version
- [ ] Learn about UGent deposit mandate 

## 3. Select access level

### For journal article AAM versions

Context: This is a new pattern that we need for researchers to be able to comply to the new publication policy. They can opt out of the right to publish AAM versions of journal articles publicly after embargo.

![Image](https://user-images.githubusercontent.com/1572885/188590534-e4d64aae-90ab-4c86-bb7b-c72783d1175b.png)

- [ ] Keep the right to make your journal article publicly available in Biblio after embargo [ DD / MM / YYYY ]
- [ ]	Opt out of this right and choose an access level

If selected "Opt out of this right and choose an access level" include steps for "All other document types and versions" (see all options there)

![Image](https://user-images.githubusercontent.com/1572885/188594793-c6ccf0eb-9ee6-45c8-8d9d-8d2330c5ebd9.png)

### All other document types and versions

Who can read this document on Biblio?
- [ ] Anyone (Open access)
- [ ] UGent
- [ ] Nobody (private)
- [ ] Embargo (only show below options if selected)
  - [ ] Period
  - [ ] Access after

#### Without embargo
![Image](https://user-images.githubusercontent.com/1572885/188596491-eab6010d-3301-43ed-a51c-aaf82e878151.png)

Alternative pattern
<img width="531" alt="Schermafbeelding 2022-09-06 om 11 38 44" src="https://user-images.githubusercontent.com/1572885/188601921-4ee636c0-21f6-4f48-8506-c0cce266c991.png">

#### With embargo
![Image](https://user-images.githubusercontent.com/1572885/188596670-65636feb-50b8-4039-856e-c41e5b6a5449.png)

Alternative pattern
<img width="574" alt="Schermafbeelding 2022-09-06 om 11 37 45" src="https://user-images.githubusercontent.com/1572885/188601772-ca883de9-ee73-4af7-9f9f-3d7b375cb7f6.png">

## 4. Select license
How can others use this document?
- [ ] Select license
- [ ] Learn about licenses
![Image](https://user-images.githubusercontent.com/1572885/188591178-1b4464aa-c86a-475f-9311-35d9407312f7.png)

- [ ] Other license (only visible if "selected other")
![Image](https://user-images.githubusercontent.com/1572885/188591295-917c49a7-1450-4caa-9c63-0c99b54ef859.png)

Alternative, non-conditional pattern:
![Image](https://user-images.githubusercontent.com/1572885/188598880-fac4616b-3519-4eb7-8b31-2446df633af9.png)

**Comment by mietcls** [comment]
Will pick this up with new quick import. Rethinking automisation.
