### ISSUE TITLE
As a researcher and as a librarian, I can see a timeline with events and communication of a record

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#569]
# Story

As a researcher and as a librarian, I can see a timeline with events and communication of a record

## Success criteria
- [ ] As a librarian, I can add a message to a record by adding it to the Biblio activity timeline for researchers and librarians to see.
- [ ] When a message is added to a record in the Biblio activity **timeline**, it is seen (as the only message) in the list overview on the record list item – visible to see to researchers and reviewers.
- [ ] When a message is added to a record in the Biblio activity **timeline**, an indication of a new message is visible in the records' "Biblio activity tab" until it is resolved.
- [ ] When a message is added to a record in the Biblio activity **timeline**, it is visible in the biblio activity timeline for researchers and reviewers.

# Context

Related https://github.com/ugent-library/biblio-backend/issues/512
