### ISSUE TITLE
[TBD] I can add datasets to Biblio – and optionally link them an existing publication

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#614]
We decided not to.

*Story*

As a researcher, I can add my datasets, so they can get reviewed by the Boekentoren and published to the world.

**Success criteria**

- [ ] Researchers find their way to the new interface with a clear button.
- [ ] Researchers are informed of this temporarily solution and future plans, so they don't get lost.
- [ ] Researchers discover how to add their datasets.
- [ ] Researchers add their datasets, and understand how to link them to their publications.
- [ ] Researchers know how to find their way back to their publications.

**Context**

To make sure we can build and release our new Biblio interface, we can temporarily redirect our researchers from the old interface to the new interface where they can add datasets.

**Tasks**

- [ ] A new button appears on the top right next to "Add new publication" with label "Add new Dataset". This button takes you to the new Biblio interface.

![Image](https://user-images.githubusercontent.com/1572885/166670527-fa274040-4b72-4fff-850a-1d224f18abb6.png)

- [ ] [TASK UNDER CONSTRUCTION] The new Biblio interface informs the researcher of the new environment, the upcoming changes and contact details in a message on top. *message content and position to be reviewed

![Image](https://user-images.githubusercontent.com/1572885/166672919-49a3fe11-a107-4f26-9c68-f8c42e8dac8b.png)

- [ ] [TASK UNDER CONSTRUCTION] In the left sidebar, you can select "Datasets" to complete the goal. The other applications are hidden for now. *topbar to be reviewed

![Image](https://user-images.githubusercontent.com/1572885/166674208-932105b9-8d6d-4daf-b9b4-0bdefa2fd50e.png)

- [ ] [TASK UNDER CONSTRUCTION] In the old interface, you can link publications to their datasets, or add them within the publication. *also adding?

![Image](https://user-images.githubusercontent.com/1572885/166675734-0b77948b-fbf1-4bc5-be74-9cf50298dea5.png)

![Image](https://user-images.githubusercontent.com/1572885/166675896-2a20bcad-13dd-4db5-b552-48d114e8dd37.png)

![Image](https://user-images.githubusercontent.com/1572885/166675829-1f278a6e-09ff-46fb-bde6-5cc35c505cb2.png)

- [ ] [TASK UNDER CONSTRUCTION] In the old interface, reviewers can filter on publications that have a dataset? *how will they find datasets?

**Additional information**

In the future this flow will disappear completely when the new review and research interface get introduced.

**Examples**

***Button old interface***
```
<li style="padding-left:12px;">
    <div id="add_new_button">
        <a href="https://biblio.ugent.be/librecat/record/new" class="btn btn-primary btn-block helpme" data-placement="left" title="" data-original-title="Create a new dataset in Biblio."><span class="fa fa-plus"></span> Add new Dataset</a>
    </div>
</li>
```

***Alert new interface***
[https://biblio-backend-ugent-prototype.vercel.app/styleguide/b-alerts.html](https://biblio-backend-ugent-prototype.vercel.app/styleguide/b-alerts.html)

```
<div class="alert alert-info">
    <i class="if if-info-circle-filled"></i>
    <p><strong>Introducing our new Biblio publishing environment.</strong> This is what our publication flow will look like in the future. Stay tuned for a fresh look for Biblio and new features in the upcoming year.
    <br />
        Got any questions? [Get in touch](mailto:test@biblio.gent).
    </p>
</div>
```
