### ISSUE TITLE
Full text & Files epic

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#650]
# Story

As a researcher, administrative support or librarian I can add the correct access level and license to my full text and documents.

## Context

Extended version: https://github.com/ugent-library/biblio-backend/issues/559 [out of scope]

# Success criteria

- [x] #651
- [x] I can upload a document
- [x] #653
- [x] #655
- [x] #656
- [ ] #659
- [x] Rename `Full text` to `Full text & Files`
- [x] #660
- [x] https://github.com/ugent-library/biblio-backend/issues/724

# Flow

**Inform people of new publication policy**
  - no checkbox needed [TBC]

**Fill out document details** `Logic: hide/show publication version field and info`
  - If full text: show publication version and information about full text
  - If no full text: do not show publication version nor full text information

**Select access levels** `Logic: hide/show embargo fields`
  - Select one out of 4 access levels
  - If selected embargoed access: show embargo fields

**[only when embargo selected]**
  - Select embargo end
  - Select access during
  - Select access after

**Select license**
- One of the predefined CC licenses
- No license
- Other license
- I don't know.

<img width="1945" alt="02 Flowchart · flowchart simple v4" src="https://user-images.githubusercontent.com/1572885/194043587-c618b4bd-3cb3-425c-bbdf-14371bf7b417.png">

Live flow:
https://www.figma.com/file/LRiABmAFa0kr338eRmBt0U/full-text-attachments-V2?node-id=18%3A2694

# Designs

No logic addressed:
![Group 103](https://user-images.githubusercontent.com/1572885/193579649-f06862c2-0fcd-48cf-8123-8fce05c18a5e.png)

Logic addressed:
![Group 104](https://user-images.githubusercontent.com/1572885/193579657-e96d0325-cd3f-4d1b-87f8-756161290f1d.png)

# Full modal example code
```
<div class="modal-dialog modal-dialog-centered modal-fullscreen modal-dialog-scrollable" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h2 class="modal-title">Document details for file 187908137-6f71459f-0e1e-4f53-b7ee-f5ec9647baed.png</h2>
    </div>
    <div class="modal-body file-attributes">
      <h3 class="mb-4">Document information</h3>
      <!-- See specific story -->
      <h3 class="mb-3">Who can access this document?</h3>
      <!-- See specific story -->
      <h4 class="mb-3">Set your embargo</h4>
      <!-- See specific story -->
      <h3 class="mb-3">Who can reuse your document?</h3>
      <!-- See specific story -->
    </div>
    <div class="modal-footer">
      <div class="spinner-border">
          <span class="sr-only"></span>
      </div>
      <button class="btn btn-link modal-close">Cancel</button>
      <button class="btn btn-primary modal-close">Save</button>
    </div>
  </div>
</div>
```

**Comment by netsensei** [comment]
As discussed: I've swapped out the access levels "open_access", "local" and "closed" for the OpenAIRE access levels in https://github.com/ugent-library/biblio-backend/commit/dca129cfe23887190d61d046553f794fc739564e:

```
"info:eu-repo/semantics/openAccess",
"info:eu-repo/semantics/restrictedAccess",
"info:eu-repo/semantics/closedAccess",
"info:eu-repo/semantics/embargoedAccess",
```

**Comment by nics** [comment]
@mietcls can be closed after review I think?

**Comment by netsensei** [comment]
Closing this. Keeping #659 open and treating it separately.
