### ISSUE TITLE
prepare LibreCat migration

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backoffice#668]
- [x] import command that keeps the librecat timestamps (will fix changing timestamps)
- [x] #737
- [x] #706
- [x] #718
- ~~warming up strategy (trigger thumbnail generation for all existing files)~~ (fix later when reintroducing imagor)
- [x] #722
- [x] https://github.com/ugent-library/biblio-backoffice/issues/783

Validation issues that need to be addressed:

- [x] publication.abstract.id.required
         solution: assign automatically in export script
- [x] publication.file.access_level_after_embargo.invalid
         solution: remove invalid embargo
- [x] publication.defense_place.required
         solution: flag as legacy
- [x] publication.defense_date.required
         solution: flag as legacy
- [x] publication.defense_time.required
         solution: flag as legacy
- [ ] publication.defense_date.invalid
         proposed solution: fix individually or just remove invalid dates
- [ ] publication.defense_time.invalid
         proposed solution: fix individually or just remove invalid dates
- [x] publication.lay_summary.id.required
         solution: assign automatically in export script
- [x] publication.author.min_ugent_authors
         solution: flag as legacy
- [x] publication.editor.min_ugent_editors
         solution: flag as legacy
- [ ] publication.author.required
         proposed solution: fix individually or flag records
- [ ] publication.editor.required
         proposed solution: fix individually or flag records
- [x] publication.supervisor.required
         solution: flag as legacy
- [x] publication.classification.invalid
         solution: assign based on type or assign default U
- [x] publication.journal_article.publication.required
         solution: flag as legacy
- [x] publication.year.required
         solution: flag as legacy
- [x] publication.id.required
         (caused by empty json objects in export)
- [x] publication.file.relation.invalid (only when using the command, not the client)
         solution: map relation data_set to supplementary_material
- [x]  publication.file.size.empty
         solution: remove file metadata

- [x] why does biblio backend only contain 294750 non deleted publications vs librecat 330801 (when using the client, not the command, to add the records)?

- [x] Validation rules need to be improved:

For example, checking the format of the year field should always happen, not only when the record is public:
```
	if p.Status == "public" {
		if p.Year == "" {
			errs = append(errs, &validation.Error{
				Pointer: "/year",
				Code:    "publication.year.required",
			})
		} else if !validation.IsYear(p.Year) {
			errs = append(errs, &validation.Error{
				Pointer: "/year",
				Code:    "publication.year.invalid",
			})
		}
	}
```

**Legacy flag semantics**
- flag is only editable by curator
- flagged record is only editable by curator
- makes defense date, time, place, supervisor not required for public dissertation
- makes year not required for public record
- makes ugent author or editor not required for public records that require them
- makes publication not required for public journal articles

**Comment by nics** [comment]
timestamp issue is fixed by #703

**Comment by mietcls** [comment]
Is #433 related here?

**Comment by mietcls** [comment]
Proposition to explain it like this to the Biblio team, so we can continue and give ourselves the time to rectify it as a team.

```
Beste Biblio Team!

Bij bepaalde oude records uit een ver verleden zitten wat foutjes (geen valide input of ontbreken van verplichte informatie). Wanneer je deze wil bewerken, kan je ze niet meer zomaar opslaan zonder alle verplichte velden correct in te vullen omdat ze niet meer valideren.

Het ontwikkelteam zal volgende oplossingen implementeren om deze records te laten valideren. Deze oplossingen zouden eventueel ook in de toekomst handig kunnen zijn voor andere records.

Datum, tijd en locatie (`#X` publicaties)
- Bij publicaties zonder **publication year**, wordt nu nu “s.d.” ingevuld.
- Bij publicaties zoals conference contributions zonder **defense date**, wordt nu nu “s.d.” ingevuld.
- Bij publicaties zoals conference contributions zonder **defense time**, wordt nu “s.d.” ingevuld.
- Bij publicaties zoals conference contributions zonder **defense locatie**, wordt nu “s.l” ingevuld. 

- Indien er vroeger fouten werden ingevuld bij bovenstaande velden, worden die nu gecorrigeerd of met bovenstaande waarden aangevuld.
- Bovenstaande publicaties worden gevlagd met de librarian tag “validation-sd” en “validation-sl” – zodat we dit nog eenvoudig kunnen dubbelchecken indien nodig
- In de toekomst, laten we het nu dus ook toe om s.d. en s.l. in te vullen. 

People & Affiliations (`#X` publicaties)
- Het label voor het vinkje “Published while none of the authors are employed at UGent” wordt aangepast naar “Published while none of the contributors were employed at UGent” om de lading te dekken. 

- `TBD` Bij publicaties waarbij affiliated UGent authors, editors of supervisors verplicht zijn, en waarvan het ID ontbreekt, wordt nu automatisch: 
    - “Published while none of the contributors were employed at UGent” aangevinkt;
    - de librarian tag “validation-people” toegevoegd;
    - een message toegevoegd over wie het gaat “UGent author: name lastname”. 
- `TBD` Bij publicaties waar er geen authors, editors of supervisors toegevoegd werden waar het verplicht is, wordt nu automatisch:
    - Een externe author of editor toegevoegd met als naam “Unknown Contributor”;
    - “Published while none of the contributors were employed at UGent” aangevinkt;
    - de librarian tag “validation-people” toegevoegd.

Journal article publisher
- Voor journal articles zonder publisher wordt er nu automatisch:
    - “Unknown” ingevuld
    - de librarian tag “validation-publisher” toegevoegd;

Andere validaties (`#X` publicaties)
- `TBC` Invalid embargos worden goed gezet. Aangezien het hier om oude publicaties gaat, zal dit geen impact hebben op access niveaus.
- Publicaties waar er geen valid classificatie is, worden nu als “U” geclassificeerd. Deze worden dan zichtbaar in jullie workflow.

We kunnen deze records later eenvoudig terugvinden door gebruik te maken van de librarian tag. Dit is niet dringend, omdat dit over oude publicaties gaat, maar het geeft ons de flexibiliteit om het later recht te zetten indien nodig.

Moesten jullie nog vragen hebben, laat het gerust weten. We kunnen hier vanaf `TBD` vandaag op testen.

Met vriendelijke groet

```

The rest of the validation issues such as abstract and lay summary seem like invisible solutions we definitely need, but will not impact the review process. Is that correct?

**Comment by nics** [comment]
@mietcls these are the remaining errors that need to be resolved manually
[remaining_errors.txt](https://github.com/ugent-library/biblio-backend/files/9811849/remaining_errors.txt)

**Comment by mietcls** [comment]
If needed; we can add legacy tag if this does not work out short term

**Comment by mietcls** [comment]
Some will have to be manually solved upon launch.

**Comment by nics** [comment]
fait accompli
