### ISSUE TITLE
Epic: Getting ready for deployment

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#777]
# Epic

Todo's for the launch

## Prep work (week of 7 November)
- #778
- #780
- #640 
- https://github.com/ugent-library/biblio-backoffice/issues/767
- #783
- https://github.com/ugent-library/biblio-backoffice/issues/767
- #781
- [x] clean up old or unneeded files in /vol/biblio to free up some extra disk space

## Launch 15 November
- #782
- https://github.com/ugent-library/biblio-backoffice/issues/765
- #784
- #773  
- #785
- #779
- #786
- #790
- #789
- #788

## After launch 16 november

- [x] https://github.com/ugent-library/biblio-backoffice/issues/766
- [x] https://github.com/ugent-library/biblio-backoffice/issues/768
- [x] #787
- [x] Prepare launch presentation
- [ ] Discuss future way of work with Inuits (ownership, account manager, proactivity, a trajectory ≠ loose tickets)
- [x] remove old backend* + dev librecat databases
- [x] remove old backend* + dev librecat indexes
- [x] remove docker containers+images on eliot*
- [x] remove temporal container + db's on eliot1
~~- [ ] make gismo oai diff~~
- [ ] investigate export/import errors + 1 publication was not migrated
       /vol/share/nsteenla/filtered_files_fixed.jsonl
      /vol/share/nsteenla/pubs_with_fixed_sizes.jsonl
- [x] #826
- [x] document gide scripts
- [x] export librecat history table for archiving (/vol/share/nsteenla/librecat_publication_versions.jsonl)
- [x] puppetize changes on persse* (see https://redmine.inuits.eu/issues/103482)
- [ ] #849
- [ ] archive backoffice logs

## After launch ±31 januari
-  [ ] remove old production librecat* indexes, databases, files, rpm

**Comment by mietcls** [comment]
Can we remove this issue? What needs to be split off into new issues?

**Comment by mietcls** [comment]
Should we move this to the new milestone Q1? @nics

**Comment by nics** [comment]
remaining cleanup tasks gathered here: https://github.com/ugent-library/biblio-backoffice/issues/1000
