### ISSUE TITLE
Graceful degradation of the UI when API integrations throws errors / are unavailable

### ISSUE THREAD

**Issue by netsensei** [ugent-library/biblio-backoffice#857]
**Story**

Several UI actions - such as adding an author or a project - depend on data that needs to be fetched from 3rd party systems like the Biblio Frontend. When the calls to Biblio Frontend API fail - e.g. an error is thrown, or the API is unavailable - the UI becomes unresponsive for the end user. 

* Triggering an action by clicking on a button, or typing input doesn't happen: the UI seems to be "stuck" with on message of what's going on.
* Looking at the browser dev tools: the console is filling up with 500 internal server errors thrown by the backend.

When API integrations - such as connecting with Biblio Frontend - fail, we need to gracefully degrade the user experience.

**Success criteria**

- [ ] Identify which UI actions trigger calls to biblio frontend or other endpoints via an API.
- [ ] Determine how and when UI actions need to degrade.
- [ ] Implement a per-action error / failure handling.
- [ ] Add better error handling for failing API calls.

**Additional information**

We're looking at various classes of errors that could be thrown:

* The data returned can't be parsed because it's messy, and might need to be fixed.
* The data isn't JSON and can't be decoded.
* A non-2xx HTTP status was returned (e.g. 403, 500, 404,...)
* Networking issues (endpoint unavailable)

**Comment by mietcls** [comment]
Is this one still part of the December milestone or should we move it to next year?

**Comment by netsensei** [comment]
I think we can close this one. 

This issue was relevant when we were still fetching persons, departments and projects via the Biblio frontend API.  This has been replaced by fetching that data directly from MongoDB and ElasticSearch (see PR: #925).

This change renders this issue stale. Graceful degredation of the UI (error messages, spinners,...) were a necessity because the frontend API either caused too much latency, or was intermittently unavailable.  Directly querying MongoDB and ElasticSearch stores removes those concerns.

Proper handling of a degrading UI experience is still relevant, but refactoring the code should be gradually introduced as we re-iterate and refine the UI through discrete / concrete / targeted steps. The scope of a separate issue / epic is just too large at this point.
