### ISSUE TITLE
Missing information "Updated by"

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#864]
# Enhancehment

## Context

Adapted from bug / question

For record 01GJ500NJ4KVAGH16EMXCSVBMD the "updated by" only had the date, not the person that performed the update. This is the case when the record is last updated by a system job, not a person. This information is important to reviewers. In this specific case they miss information about who updated it before the system update. They won't know who to contact in this case (which is the person, not the system, that last updated the record).

Before review:
![Image](https://user-images.githubusercontent.com/1572885/204497505-88b8493d-8d2d-48c0-a6ca-044a28d3a82a.png)

After review, it did show up:
![Image](https://user-images.githubusercontent.com/1572885/204497574-4068bf66-d125-4bf2-b613-a92d2aea2de2.png)

## Needs 

- [x] Know who created the record
- [x] Creation date (in specific hours and dates)
- [x] Know who updated the record last
- [x] Last updated date (in specific hours and dates)
- [x] Know who updated the record in between
- [x] Updated date in between (in specific hours and dates)

Current implementation:
- We know who created the record
- We know approximately when ("two weeks ago")
- We know who / what lastly updated the record
- We when the last update happened approximately ("two weeks ago")

**Comment by nics** [comment]
@mietcls user is empty when the records is last updated by a system job

**Comment by mietcls** [comment]
Okay, I'll start working on a minimal version for "history". Depending on our priorities we can pick it up later.

**Comment by mietcls** [comment]
Will be picked up in an other form

**Comment by mietcls** [comment]
Will be picked up in an other form
